name: RoleplayingGames
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8998426329344511
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4071146761998534
  lightness: 0.34156613145023584
  saturation: 0.3078127366025001
  rhythmicContrast: 0.7332601302769035
purpose: []
